create table profile (
    id bigint generated by default as identity,
    name varchar(255) not null,
    birthday date,
    primary key (id)
);

insert into profile (
    id,
    name,
    birthday
) values (
    1,
    'init',
    '1900-1-1'
)