create table profile (
    id bigint generated by default as identity,
    name varchar(255) not null,
    birthday date,
    primary key (id)
);

create table basic_type (
    integer_type integer,         -- Mapped to java.lang.Integer
    long_type bigint,             -- Mapped to java.lang.Long
    boolean_type boolean,         -- Mapped to java.lang.Boolean
    float_type real,              -- Mapped to java.lang.Float
    double_type double precision, -- Mapped to java.lang.Double
    biginteger_type numeric,      -- Mapped to java.math.BigInteger
    bigdecimal_type decfloat,     -- Mapped to java.math.BigDecimal
    string_type varchar,          -- Mapped to java.lang.String
    byte_array_type blob,         -- Mapped to byte[]
    primary key (integer_type)
);

create table datetime_type (
    integer_type integer,         -- Mapped to java.lang.Integer
    date_type date,               -- Mapped to java.sql.Date or java.time.LocalDate
    time_type time(9),            -- Mapped to java.sql.Time or java.time.LocalTime
    timestamp_type timestamp(9),  -- Mapped to java.sql.Timestamp or java.time.LocalDateTime
    primary key (integer_type)
);
